# Generated by Django 5.0.4 on 2024-04-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.corpus', verbose_name='Корпус')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department', verbose_name='Отделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.medicalorganization', verbose_name='Организация')),
                ('plan_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.plansubtype', verbose_name='Подтип плана')),
            ],
            options={
                'verbose_name': 'План отделения',
                'verbose_name_plural': 'Планы отделений',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'Январь'), ('02', 'Февраль'), ('03', 'Март'), ('04', 'Апрель'), ('05', 'Май'), ('06', 'Июнь'), ('07', 'Июль'), ('08', 'Август'), ('09', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=2, verbose_name='Месяц')),
                ('plan_integer', models.IntegerField(default=0, verbose_name='Талоны')),
                ('plan_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Финансы')),
                ('plan_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plandepartment', verbose_name='План отделения')),
            ],
            options={
                'verbose_name': 'Месячный план отделения',
                'verbose_name_plural': 'Месячные планы отделений',
            },
        ),
        migrations.CreateModel(
            name='PlanDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.corpus', verbose_name='Корпус')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department', verbose_name='Отделение')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='structure.doctor', verbose_name='Врач')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.medicalorganization', verbose_name='Организация')),
                ('plan_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.plansubtype', verbose_name='Подтип плана')),
            ],
            options={
                'verbose_name': 'План врача',
                'verbose_name_plural': 'Планы врачей',
            },
        ),
        migrations.CreateModel(
            name='PlanRecordDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'Январь'), ('02', 'Февраль'), ('03', 'Март'), ('04', 'Апрель'), ('05', 'Май'), ('06', 'Июнь'), ('07', 'Июль'), ('08', 'Август'), ('09', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=2, verbose_name='Месяц')),
                ('plan_integer', models.IntegerField(default=0, verbose_name='Талоны')),
                ('plan_money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Финансы')),
                ('plan_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plandoctor', verbose_name='План отделения')),
            ],
            options={
                'verbose_name': 'Месячный план врача',
                'verbose_name_plural': 'Месячные планы врачей',
            },
        ),
    ]
