# Generated by Django 5.0.4 on 2024-04-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(default='-', max_length=255, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='MedicalOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('short_name', models.CharField(default='-', max_length=255, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='PlanSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(default='-', max_length=200, verbose_name='Описание')),
                ('list_targets', models.CharField(default='-', max_length=200, verbose_name='Цели ОМС')),
            ],
            options={
                'verbose_name': 'Подтип плана',
                'verbose_name_plural': 'Подтипы плана',
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(default='-', max_length=200, verbose_name='Описание')),
                ('list_targets', models.CharField(default='-', max_length=200, verbose_name='Цели ОМС')),
            ],
            options={
                'verbose_name': 'Тип плана',
                'verbose_name_plural': 'Типы планов',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(default='-', max_length=255, verbose_name='Краткое название')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.corpus')),
                ('plan_subtypes', models.ManyToManyField(blank=True, to='structure.plansubtype', verbose_name='Подтип плана')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'unique_together': {('name', 'building')},
            },
        ),
        migrations.AddField(
            model_name='corpus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.medicalorganization'),
        ),
        migrations.AddField(
            model_name='plansubtype',
            name='plan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.plantype'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.CharField(max_length=20, verbose_name='СНИЛС')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('start_date', models.DateField(verbose_name='Дата приема')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('certificate_validity_date', models.DateField(blank=True, null=True, verbose_name='Сертификат действителен по:')),
                ('branch_code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reference.branchcode', verbose_name='Код отделения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department', verbose_name='Отделение')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reference.profile', verbose_name='Профиль')),
                ('specialty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reference.specialty', verbose_name='Специальность')),
                ('structural_subdivision', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='reference.structuralsubdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'unique_together': {('department', 'surname', 'name', 'patronymic_name', 'structural_subdivision', 'specialty')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='corpus',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='plansubtype',
            unique_together={('name', 'plan_type')},
        ),
    ]
